### ISSUE TITLE
当布局未完成时，重新改变布局会报错

### ISSUE THREAD

**Issue by GavinHe322** [shichuanpo/cytoscape.js-d3-force#3]
#### 该库流畅度很高，是一个很棒的开源项目，但在使用过程遇到以下问题

**依赖**
  - cytoscape: "^3.13.0",
  - cytoscape-d3-force: "^1.1.0"

**发生了什么事**
当布局未完成 重复调用函数时，会报错 **Cannot read property 'notify' of null**

**复现**
将您仓库的 ```demo.html``` 文件 **149 行 ~ 190** 行拿函数包住，调用两次
```js
 document.addEventListener('DOMContentLoaded', function () {
      function run() {
        var cy = window.cy = cytoscape({
            ...
        })
      }
      run()
      run()
  });
```

**Comment by denglouhen** [comment]
是的，我也发现了这个问题
