### ISSUE TITLE
通过 layout.run 修改为其他布局时，出现怪异情况

### ISSUE THREAD

**Issue by GavinHe322** [shichuanpo/cytoscape.js-d3-force#5]
#### 哈哈哈 你好大佬 又是我

**依赖**
  - cytoscape: "^3.13.0",
  - cytoscape-d3-force: "^1.1.2"

**发生了什么事**
当使用该库生成 d3-force 布局时，在将布局修改成 cy.js 内置布局（'cose', 'grid', 'circle'）时会出现怪异情况

**复现**
```js
// 1. 使用 chrome 打开 demo.html
// 2. 打开控制台输入如下，改变布局
/**
var options = {
    name: 'cose' || 'grid' || 'circle'
  }
cy.layout( options ).run()
*/
// 3.随意拖动一个节点，可发现未变成新的布局
```

**Comment by shichuanpo** [comment]
因为当前布局还没完成吧
建议：layout.stop后再去切换布局
