### ISSUE TITLE
IE控制台报错语法错误

### ISSUE THREAD

**Issue by denglouhen** [shichuanpo/cytoscape.js-d3-force#6]
在vue的单文件里引入：
```
import d3Force from "cytoscape-d3-force";
cytoscape.use(d3Force);
```

然后在IE启动项目后控制台打印错误：
 
![image](https://user-images.githubusercontent.com/26452618/81519524-28e7f100-9374-11ea-91a2-f3fee1153e6d.png)

**Comment by denglouhen** [comment]
我注释掉引入就不会报错了，这个layout插件有兼容IE吗？

**Comment by shichuanpo** [comment]
请看linkId配置，应该是linkId配置没加；兼容性参考cytoscapejs和d3-force

**Comment by denglouhen** [comment]
不是那个原因，我的项目一进来的布局并不是d3-force。在chrome上是不会出错的，用IE打开就出错。

**Comment by denglouhen** [comment]
你可以理解为我只是引入了一下，但没有使用这个布局，IE就会报错。

**Comment by denglouhen** [comment]
话说项目的demo.html也在IE下打不开

**Comment by shichuanpo** [comment]
> 话说项目的demo.html也在IE下打不开

看上去像是d3-force的报错，IE几的版本
